/**
 * MANUAL ENVIRONMENT VARIABLES SETUP
 * 
 * This is a temporary solution if you're having issues with .env files.
 * Simply edit this file with your actual API keys, then run:
 * 
 * node scripts/manual-env.js
 * 
 * It will create a .env.local file with your settings.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// =================================================================
// EDIT THESE VALUES WITH YOUR ACTUAL KEYS
// =================================================================

const CLERK_PUBLISHABLE_KEY = 'pk_test_bWFzc2l2ZS1naG91bC00NC5jbGVyay5hY2NvdW50cy5kZXYk';
const CONVEX_URL = 'https://tame-herring-312.convex.cloud'; // Keep this URL

// =================================================================
// DO NOT EDIT BELOW THIS LINE
// =================================================================

// Create the .env.local file content
const envContent = `# This file was generated by scripts/manual-env.js
# Last updated: ${new Date().toISOString()}

# Clerk authentication
VITE_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}

# Convex API URL
VITE_CONVEX_URL=${CONVEX_URL}

# Note: If you update your API keys, either edit this file
# and run 'node scripts/manual-env.js' again, or directly
# edit this .env.local file.
`;

// Path where to save the .env.local file
const envPath = path.resolve(__dirname, '..', '.env.local');

// Write the file
try {
  fs.writeFileSync(envPath, envContent);
  console.log('✅ Successfully created .env.local file!');
  console.log(`📄 File location: ${envPath}`);
} catch (error) {
  console.error('❌ Error creating .env.local file:', error.message);
} 